/**
 * Simple Node.js script to load .env and generate env-config.js
 * Run this script before serving the frontend to inject env variables
 * 
 * Usage: node load-env.js
 * 
 * This creates a script tag that can be included in HTML to load env vars
 */

const fs = require('fs');
const path = require('path');

// Load .env file
function loadEnv() {
    const envPath = path.join(__dirname, '.env');
    const env = {};
    
    if (fs.existsSync(envPath)) {
        const envContent = fs.readFileSync(envPath, 'utf8');
        const lines = envContent.split('\n');
        
        for (const line of lines) {
            const trimmed = line.trim();
            // Skip comments and empty lines
            if (trimmed && !trimmed.startsWith('#')) {
                const [key, ...valueParts] = trimmed.split('=');
                if (key && valueParts.length > 0) {
                    const value = valueParts.join('=').trim();
                    env[key.trim()] = value;
                }
            }
        }
    }
    
    return env;
}

// Generate env-config.js
function generateEnvConfig() {
    const env = loadEnv();
    const envJson = JSON.stringify(env, null, 2);
    
    const configContent = `// Auto-generated from .env file
// DO NOT EDIT - This file is generated by load-env.js
// Run: node load-env.js to regenerate

(function() {
    if (typeof window !== 'undefined') {
        window._env = ${envJson};
    }
})();
`;
    
    const outputPath = path.join(__dirname, 'env-config.js');
    fs.writeFileSync(outputPath, configContent, 'utf8');
    console.log('✅ Generated env-config.js from .env file');
    console.log(`   Loaded ${Object.keys(env).length} environment variables`);
}

// Run if executed directly
if (require.main === module) {
    generateEnvConfig();
}

module.exports = { loadEnv, generateEnvConfig };

