const fs = require('fs');
const path = require('path');

// Load .env file and parse into structured object
function loadEnv() {
    const envPath = path.join(__dirname, '.env');

    // Default Structure
    const processed = {
        API_BASE_URL: "http://localhost:5000/api",
        FIREBASE: {},
        WHATSAPP: {
             DOCTOR_Aakash: {}
        },
        APP: {
            AI_ENABLED: true,
            MAX_FILE_SIZE: 10 * 1024 * 1024,
            SUPPORTED_FORMATS: ["image/jpeg", "image/png", "image/webp"]
        }
    };

    if (fs.existsSync(envPath)) {
        console.log('Reading .env file...');
        const envContent = fs.readFileSync(envPath, 'utf8');
        const lines = envContent.split('\n');

        for (const line of lines) {
            const trimmed = line.trim();
            if (trimmed && !trimmed.startsWith('#')) {
                const parts = trimmed.split('=');
                if (parts.length < 2) continue;

                const key = parts[0].trim();
                const value = parts.slice(1).join('=').trim();

                // Mapping Logic
                if (key === 'API_BASE_URL') processed.API_BASE_URL = value;

                // Firebase
                else if (key === 'FIREBASE_API_KEY') processed.FIREBASE.apiKey = value;
                else if (key === 'FIREBASE_AUTH_DOMAIN') processed.FIREBASE.authDomain = value;
                else if (key === 'FIREBASE_PROJECT_ID') processed.FIREBASE.projectId = value;
                else if (key === 'FIREBASE_STORAGE_BUCKET') processed.FIREBASE.storageBucket = value;
                else if (key === 'FIREBASE_MESSAGING_SENDER_ID') processed.FIREBASE.messagingSenderId = value;
                else if (key === 'FIREBASE_APP_ID') processed.FIREBASE.appId = value;
                else if (key === 'FIREBASE_MEASUREMENT_ID') processed.FIREBASE.measurementId = value;

                // WhatsApp
                else if (key === 'WHATSAPP_DOCTOR_Aakash_NAME') processed.WHATSAPP.DOCTOR_Aakash.name = value;
                else if (key === 'WHATSAPP_DOCTOR_Aakash_PHONE') processed.WHATSAPP.DOCTOR_Aakash.phone = value;
                else if (key === 'WHATSAPP_DOCTOR_Aakash_WHATSAPP') processed.WHATSAPP.DOCTOR_Aakash.whatsapp = value;

                // App Config
                else if (key === 'AI_ENABLED') processed.APP.AI_ENABLED = (value.toLowerCase() === 'true');
                else if (key === 'MAX_FILE_SIZE') processed.APP.MAX_FILE_SIZE = parseInt(value);
                else if (key === 'SUPPORTED_FORMATS') processed.APP.SUPPORTED_FORMATS = value.split(',').map(s => s.trim());
            }
        }
    } else {
        console.log('No .env file found, using defaults.');
    }

    return processed;
}

// Generate env-config.js
function generateEnvConfig() {
    const env = loadEnv();
    const envJson = JSON.stringify(env, null, 2);

    const configContent = `// Auto-generated from .env file
// DO NOT EDIT - This file is generated by load-env.js
// Run: node load-env.js to regenerate

(function() {
    if (typeof window !== 'undefined') {
        window.ENV = ${envJson};
    }
})();
`;

    const outputPath = path.join(__dirname, 'env-config.js');
    fs.writeFileSync(outputPath, configContent, 'utf8');
    console.log('✅ Generated env-config.js with env structure');
}

// Run if executed directly
if (require.main === module) {
    generateEnvConfig();
}

module.exports = { loadEnv, generateEnvConfig };
